# Generated by Django 2.1.7 on 2019-03-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='greeter.Topping'),
        ),
    ]
