# Generated by Django 2.1.7 on 2019-03-28 00:58

from django.db import migrations, models
import django.db.models.deletion
import menu.models.origin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('stock', models.CharField(choices=[('IN STOCK', 'In stock'), ('OUT OF STOCK', 'Out of stock'), ('RESTOCKING SOON', 'Restocking soon')], default='IN STOCK', max_length=16)),
                ('translation', models.CharField(blank=True, default='', max_length=64)),
                ('punchline', models.CharField(blank=True, default='', max_length=64)),
                ('bartender_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=255)),
                ('data', models.ImageField(upload_to='images')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=-1)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('latitude', models.CharField(max_length=16, validators=[menu.models.origin.ValidateCoordinate('Latitude', -90.0, 90.0)])),
                ('longitude', models.CharField(max_length=16, validators=[menu.models.origin.ValidateCoordinate('Longitude', -180.0, 180.0)])),
                ('grower_name', models.CharField(max_length=64)),
                ('grower_notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='TeaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('stock', models.CharField(choices=[('IN STOCK', 'In stock'), ('OUT OF STOCK', 'Out of stock'), ('RESTOCKING SOON', 'Restocking soon')], default='IN STOCK', max_length=16)),
                ('translation', models.CharField(blank=True, default='', max_length=64)),
                ('punchline', models.CharField(blank=True, default='', max_length=64)),
                ('bartender_notes', models.TextField(blank=True, default='')),
                ('tasting_notes', models.CharField(blank=True, default='', max_length=64)),
                ('year', models.CharField(blank=True, default=2019, max_length=4)),
                ('leaves', models.CharField(blank=True, default='', max_length=64)),
                ('price_bar', models.CharField(blank=True, default='', max_length=16)),
                ('price_bowl', models.CharField(blank=True, default='', max_length=16)),
                ('price_shot', models.CharField(blank=True, default='', max_length=16)),
                ('price_retail', models.CharField(blank=True, default='', max_length=32)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Image')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Origin')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Category')),
                ('short_description', models.CharField(blank=True, default='', max_length=64)),
                ('long_description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'item categories',
            },
            bases=('menu.category',),
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Category')),
            ],
            options={
                'verbose_name_plural': 'menu categories',
            },
            bases=('menu.category',),
        ),
        migrations.AlterUniqueTogether(
            name='origin',
            unique_together={('latitude', 'longitude')},
        ),
        migrations.AddField(
            model_name='fooditem',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Image'),
        ),
        migrations.AddField(
            model_name='teaitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ItemCategory'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='menu_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MenuCategory'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ItemCategory'),
        ),
    ]
