# Generated by Django 2.1.7 on 2019-03-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190322_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='teaitem',
            options={'ordering': ['-order']},
        ),
    ]
