# Generated by Django 2.1.7 on 2019-03-12 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190311_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Category')),
            ],
            options={
                'verbose_name_plural': 'item categories',
            },
            bases=('menu.category',),
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Category')),
            ],
            options={
                'verbose_name_plural': 'menu categories',
            },
            bases=('menu.category',),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ItemCategory'),
        ),
        migrations.AlterField(
            model_name='teaitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ItemCategory'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MenuCategory'),
        ),
    ]
