# Generated by Django 2.1.7 on 2019-03-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190312_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teaitem',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
