# Generated by Django 2.1.7 on 2019-03-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190322_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teaitem',
            options={},
        ),
    ]
