# Generated by Django 2.1.7 on 2019-03-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20190312_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='grower',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
