# Generated by Django 2.1.7 on 2019-03-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20190312_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='stock',
            field=models.CharField(choices=[('IN STOCK', 'In stock'), ('OUT OF STOCK', 'Out of stock'), ('RESTOCKING SOON', 'Restocking soon')], default='IN STOCK', max_length=16),
        ),
        migrations.AddField(
            model_name='teaitem',
            name='stock',
            field=models.CharField(choices=[('IN STOCK', 'In stock'), ('OUT OF STOCK', 'Out of stock'), ('RESTOCKING SOON', 'Restocking soon')], default='IN STOCK', max_length=16),
        ),
    ]
