# Generated by Django 2.1.7 on 2019-03-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20190313_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='translation',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='teaitem',
            name='translation',
            field=models.CharField(default='', max_length=64),
        ),
    ]
