# Generated by Django 2.1.7 on 2019-03-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_teaitem_tasting_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='long_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='short_description',
            field=models.CharField(default='', max_length=64),
        ),
    ]
