# Generated by Django 2.1.7 on 2019-03-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20190313_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaitem',
            name='year',
            field=models.CharField(default=2019, max_length=4),
        ),
    ]
