# Generated by Django 2.1.7 on 2019-03-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_teaitem_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaitem',
            name='leaves',
            field=models.CharField(default='', max_length=64),
        ),
    ]
