# Generated by Django 2.1.7 on 2019-03-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20190313_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='bartender_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teaitem',
            name='bartender_notes',
            field=models.TextField(default=''),
        ),
    ]
