# Generated by Django 2.1.7 on 2019-03-13 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_auto_20190313_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='category',
            new_name='menu_category',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teaitem',
            name='description',
        ),
    ]
